$TEMPLATE[blas.group.ZDROT]
ROT
$TEMPLATE[blas.group.CSROT]
ROT
$TEMPLATE[blas.group.CDOTU]
DOT
$TEMPLATE[blas.group.ZDOTU]
DOT
$TEMPLATE[blas.group.DZASUM]
ASUM
$TEMPLATE[blas.value.DZASUM]
complex
$TEMPLATE[blas.precision.DZASUM]
double
$TEMPLATE[blas.group.SCASUM]
ASUM
$TEMPLATE[blas.value.SCASUM]
complex
$TEMPLATE[blas.precision.SCASUM]
single
$TEMPLATE[blas.group.DZNRM2]
NRM2
$TEMPLATE[blas.value.DZNRM2]
complex
$TEMPLATE[blas.precision.DZNRM2]
double
$TEMPLATE[blas.group.SCNRM2]
NRM2
$TEMPLATE[blas.value.SCNRM2]
complex
$TEMPLATE[blas.precision.SCNRM2]
single
$TEMPLATE[end]
