//
// Copyright (c) 2003--2009
// Toon Knapen, Karl Meerbergen, Kresimir Fresl,
// Thomas Klimpel and Rutger ter Borg
//
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)
//
// THIS FILE IS AUTOMATICALLY GENERATED
// PLEASE DO NOT EDIT!
//

#ifndef BOOST_NUMERIC_BINDINGS_BLAS_LEVEL3_SYRK_HPP
#define BOOST_NUMERIC_BINDINGS_BLAS_LEVEL3_SYRK_HPP

// Include header of configured BLAS interface
#if defined BOOST_NUMERIC_BINDINGS_BLAS_CBLAS
#include <boost/numeric/bindings/blas/detail/cblas.h>
#elif defined BOOST_NUMERIC_BINDINGS_BLAS_CUBLAS
#include <boost/numeric/bindings/blas/detail/cublas.h>
#else
#include <boost/numeric/bindings/blas/detail/blas.h>
#endif

#include <boost/mpl/bool.hpp>
#include <boost/numeric/bindings/traits/traits.hpp>
#include <boost/numeric/bindings/traits/type_traits.hpp>
#include <boost/static_assert.hpp>
#include <boost/type_traits/is_same.hpp>

namespace boost {
namespace numeric {
namespace bindings {
namespace blas {

// The detail namespace is used for overloads on value type,
// and to dispatch to the right routine

namespace detail {

inline void syrk( const char uplo, const char trans, const integer_t n,
        const integer_t k, const float alpha, const float* a,
        const integer_t lda, const float beta, float* c,
        const integer_t ldc ) {
#if defined BOOST_NUMERIC_BINDINGS_BLAS_CBLAS
    cblas_ssyrk( CblasColMajor, ( uplo == 'U' ? CblasUpper : CblasLower ),
            ( trans == 'N' ? CblasNoTrans : ( trans == 'T' ? CblasTrans : CblasConjTrans ) ),
            n, k, alpha, a, lda, beta, c, ldc );
#elif defined BOOST_NUMERIC_BINDINGS_BLAS_CUBLAS
    cublasSsyrk( uplo, trans, n, k, alpha, a, lda, beta, c, ldc );
#else
    BLAS_SSYRK( &uplo, &trans, &n, &k, &alpha, a, &lda, &beta, c, &ldc );
#endif
}

inline void syrk( const char uplo, const char trans, const integer_t n,
        const integer_t k, const double alpha, const double* a,
        const integer_t lda, const double beta, double* c,
        const integer_t ldc ) {
#if defined BOOST_NUMERIC_BINDINGS_BLAS_CBLAS
    cblas_dsyrk( CblasColMajor, ( uplo == 'U' ? CblasUpper : CblasLower ),
            ( trans == 'N' ? CblasNoTrans : ( trans == 'T' ? CblasTrans : CblasConjTrans ) ),
            n, k, alpha, a, lda, beta, c, ldc );
#elif defined BOOST_NUMERIC_BINDINGS_BLAS_CUBLAS
    cublasDsyrk( uplo, trans, n, k, alpha, a, lda, beta, c, ldc );
#else
    BLAS_DSYRK( &uplo, &trans, &n, &k, &alpha, a, &lda, &beta, c, &ldc );
#endif
}

inline void syrk( const char uplo, const char trans, const integer_t n,
        const integer_t k, const traits::complex_f alpha,
        const traits::complex_f* a, const integer_t lda,
        const traits::complex_f beta, traits::complex_f* c,
        const integer_t ldc ) {
#if defined BOOST_NUMERIC_BINDINGS_BLAS_CBLAS
    cblas_csyrk( CblasColMajor, ( uplo == 'U' ? CblasUpper : CblasLower ),
            ( trans == 'N' ? CblasNoTrans : ( trans == 'T' ? CblasTrans : CblasConjTrans ) ),
            n, k, traits::void_ptr(&alpha), traits::void_ptr(a), lda,
            traits::void_ptr(&beta), traits::void_ptr(c), ldc );
#elif defined BOOST_NUMERIC_BINDINGS_BLAS_CUBLAS
    cublasCsyrk( uplo, trans, n, k, traits::void_ptr(alpha),
            traits::void_ptr(a), lda, traits::void_ptr(beta),
            traits::void_ptr(c), ldc );
#else
    BLAS_CSYRK( &uplo, &trans, &n, &k, traits::complex_ptr(&alpha),
            traits::complex_ptr(a), &lda, traits::complex_ptr(&beta),
            traits::complex_ptr(c), &ldc );
#endif
}

inline void syrk( const char uplo, const char trans, const integer_t n,
        const integer_t k, const traits::complex_d alpha,
        const traits::complex_d* a, const integer_t lda,
        const traits::complex_d beta, traits::complex_d* c,
        const integer_t ldc ) {
#if defined BOOST_NUMERIC_BINDINGS_BLAS_CBLAS
    cblas_zsyrk( CblasColMajor, ( uplo == 'U' ? CblasUpper : CblasLower ),
            ( trans == 'N' ? CblasNoTrans : ( trans == 'T' ? CblasTrans : CblasConjTrans ) ),
            n, k, traits::void_ptr(&alpha), traits::void_ptr(a), lda,
            traits::void_ptr(&beta), traits::void_ptr(c), ldc );
#elif defined BOOST_NUMERIC_BINDINGS_BLAS_CUBLAS
    cublasZsyrk( uplo, trans, n, k, traits::void_ptr(alpha),
            traits::void_ptr(a), lda, traits::void_ptr(beta),
            traits::void_ptr(c), ldc );
#else
    BLAS_ZSYRK( &uplo, &trans, &n, &k, traits::complex_ptr(&alpha),
            traits::complex_ptr(a), &lda, traits::complex_ptr(&beta),
            traits::complex_ptr(c), &ldc );
#endif
}


} // namespace detail

// value-type based template
template< typename ValueType >
struct syrk_impl {

    typedef ValueType value_type;
    typedef typename traits::type_traits<ValueType>::real_type real_type;
    typedef void return_type;

    // static template member function
    template< typename MatrixA, typename MatrixC >
    static return_type invoke( const char trans, const value_type alpha,
            const MatrixA& a, const value_type beta, MatrixC& c ) {
        BOOST_STATIC_ASSERT( (boost::is_same< typename traits::matrix_traits<
                MatrixA >::value_type, typename traits::matrix_traits<
                MatrixC >::value_type >::value) );
        detail::syrk( traits::matrix_uplo_tag(c), trans,
                traits::matrix_num_columns(c),
                (trans=='N' ? traits::matrix_num_columns(a) : traits::matrix_num_rows(a)),
                alpha, traits::matrix_storage(a),
                traits::leading_dimension(a), beta, traits::matrix_storage(c),
                traits::leading_dimension(c) );
    }
};

// generic template function to call syrk
template< typename MatrixA, typename MatrixC >
inline typename syrk_impl< typename traits::matrix_traits<
        MatrixA >::value_type >::return_type
syrk( const char trans, const typename traits::matrix_traits<
        MatrixA >::value_type alpha, const MatrixA& a,
        const typename traits::matrix_traits< MatrixA >::value_type beta,
        MatrixC& c ) {
    typedef typename traits::matrix_traits< MatrixA >::value_type value_type;
    syrk_impl< value_type >::invoke( trans, alpha, a, beta, c );
}

} // namespace blas
} // namespace bindings
} // namespace numeric
} // namespace boost

#endif
