//
// Copyright (c) 2003--2009
// Toon Knapen, Karl Meerbergen, Kresimir Fresl,
// Thomas Klimpel and Rutger ter Borg
//
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)
//
// THIS FILE IS AUTOMATICALLY GENERATED
// PLEASE DO NOT EDIT!
//

#ifndef BOOST_NUMERIC_BINDINGS_BLAS_LEVEL1_AXPY_HPP
#define BOOST_NUMERIC_BINDINGS_BLAS_LEVEL1_AXPY_HPP

// Include header of configured BLAS interface
#if defined BOOST_NUMERIC_BINDINGS_BLAS_CBLAS
#include <boost/numeric/bindings/blas/detail/cblas.h>
#elif defined BOOST_NUMERIC_BINDINGS_BLAS_CUBLAS
#include <boost/numeric/bindings/blas/detail/cublas.h>
#else
#include <boost/numeric/bindings/blas/detail/blas.h>
#endif

#include <boost/mpl/bool.hpp>
#include <boost/numeric/bindings/traits/traits.hpp>
#include <boost/numeric/bindings/traits/type_traits.hpp>
#include <boost/static_assert.hpp>
#include <boost/type_traits/is_same.hpp>

namespace boost {
namespace numeric {
namespace bindings {
namespace blas {

// The detail namespace is used for overloads on value type,
// and to dispatch to the right routine

namespace detail {

inline void axpy( const integer_t n, const float a, const float* x,
        const integer_t incx, float* y, const integer_t incy ) {
#if defined BOOST_NUMERIC_BINDINGS_BLAS_CBLAS
    cblas_saxpy( n, a, x, incx, y, incy );
#elif defined BOOST_NUMERIC_BINDINGS_BLAS_CUBLAS
    cublasSaxpy( n, a, x, incx, y, incy );
#else
    BLAS_SAXPY( &n, &a, x, &incx, y, &incy );
#endif
}

inline void axpy( const integer_t n, const double a, const double* x,
        const integer_t incx, double* y, const integer_t incy ) {
#if defined BOOST_NUMERIC_BINDINGS_BLAS_CBLAS
    cblas_daxpy( n, a, x, incx, y, incy );
#elif defined BOOST_NUMERIC_BINDINGS_BLAS_CUBLAS
    cublasDaxpy( n, a, x, incx, y, incy );
#else
    BLAS_DAXPY( &n, &a, x, &incx, y, &incy );
#endif
}

inline void axpy( const integer_t n, const traits::complex_f a,
        const traits::complex_f* x, const integer_t incx,
        traits::complex_f* y, const integer_t incy ) {
#if defined BOOST_NUMERIC_BINDINGS_BLAS_CBLAS
    cblas_caxpy( n, traits::void_ptr(&a), traits::void_ptr(x), incx,
            traits::void_ptr(y), incy );
#elif defined BOOST_NUMERIC_BINDINGS_BLAS_CUBLAS
    cublasCaxpy( n, traits::void_ptr(a), traits::void_ptr(x), incx,
            traits::void_ptr(y), incy );
#else
    BLAS_CAXPY( &n, traits::complex_ptr(&a), traits::complex_ptr(x), &incx,
            traits::complex_ptr(y), &incy );
#endif
}

inline void axpy( const integer_t n, const traits::complex_d a,
        const traits::complex_d* x, const integer_t incx,
        traits::complex_d* y, const integer_t incy ) {
#if defined BOOST_NUMERIC_BINDINGS_BLAS_CBLAS
    cblas_zaxpy( n, traits::void_ptr(&a), traits::void_ptr(x), incx,
            traits::void_ptr(y), incy );
#elif defined BOOST_NUMERIC_BINDINGS_BLAS_CUBLAS
    // NOT FOUND();
#else
    BLAS_ZAXPY( &n, traits::complex_ptr(&a), traits::complex_ptr(x), &incx,
            traits::complex_ptr(y), &incy );
#endif
}


} // namespace detail

// value-type based template
template< typename ValueType >
struct axpy_impl {

    typedef ValueType value_type;
    typedef typename traits::type_traits<ValueType>::real_type real_type;
    typedef void return_type;

    // static template member function
    template< typename VectorX, typename VectorY >
    static return_type invoke( const value_type a, const VectorX& x,
            VectorY& y ) {
        BOOST_STATIC_ASSERT( (boost::is_same< typename traits::vector_traits<
                VectorX >::value_type, typename traits::vector_traits<
                VectorY >::value_type >::value) );
        detail::axpy( traits::vector_size(x), a,
                traits::vector_storage(x), traits::vector_stride(x),
                traits::vector_storage(y), traits::vector_stride(y) );
    }
};

// generic template function to call axpy
template< typename VectorX, typename VectorY >
inline typename axpy_impl< typename traits::vector_traits<
        VectorX >::value_type >::return_type
axpy( const typename traits::vector_traits< VectorX >::value_type a,
        const VectorX& x, VectorY& y ) {
    typedef typename traits::vector_traits< VectorX >::value_type value_type;
    axpy_impl< value_type >::invoke( a, x, y );
}

} // namespace blas
} // namespace bindings
} // namespace numeric
} // namespace boost

#endif
